# Generated by Django 5.2.4 on 2025-08-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=10)),
                ('units_available', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
