# Generated by Django 4.2.23 on 2025-08-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donors", "0005_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_donation",
            field=models.DateField(blank=True, null=True),
        ),
    ]
