# Generated by Django 4.2.23 on 2025-08-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donors", "0006_userprofile_last_donation"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="district",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="share_phone",
            field=models.BooleanField(default=False),
        ),
    ]
