# Generated by Django 4.2.23 on 2025-08-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donors", "0007_userprofile_district_userprofile_share_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="donated_recently",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="not_ready",
            field=models.BooleanField(default=False),
        ),
    ]
