# Generated by Django 4.2.23 on 2025-08-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_rebuild_core"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="donated_recently",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="not_ready",
            field=models.BooleanField(default=False),
        ),
    ]
